# Deploy the production cloud function if pushing to the `main` branch or the test cloud functions if pushing to the
# `test` branch.
name: gcloud-deploy

on:
  push:
    branches:
      - main
      - test

jobs:
  get-prefix:
    runs-on: ubuntu-latest
    outputs:
      name_prefix: ${{ steps.prefix.outputs.name_prefix }}
    steps:
      - name: Get prefix (test- or nothing for production)
        id: prefix
        run: |
          echo ${{ github.ref }}
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "name_prefix=" >> $GITHUB_OUTPUT
          else
            echo "name_prefix=test-" >> $GITHUB_OUTPUT
          fi

  deploy-api:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    needs: get-prefix
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/406572174402/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions@windeurope72-private.iam.gserviceaccount.com"

      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ needs.get-prefix.outputs.name_prefix }}elevations-api
          runtime: python310
          env_vars: COMPUTE_PROVIDER=GOOGLE_CLOUD_FUNCTION
          memory_mb: 1024
          region: europe-west1
          service_account_email: github-actions@windeurope72-private.iam.gserviceaccount.com
          source_dir: elevations_api
          entrypoint: get_elevations
